### ISSUE TITLE
infra.aap_configuration Dispatch - Constructed Inventories Not Created Properly

### ISSUE THREAD

**Issue by daleroux** [redhat-cop/infra.controller_configuration#24]
## Summary

The `infra.aap_configuration.dispatch` module does not create constructed inventories properly. Specifically, it skips any `limit` or `source` variables defined in the inventory resource file. As a result, the input inventory appears empty.

The following files were generated by filetree_create on a 2.4 environment:
credentials.yaml  current_credential_types.yaml  inventories.yaml  inventory_sources.yaml  organizations.yaml  projects.yaml

Using  module infra.aap_configuration.dispatch to CasC a new 2.5 environment with the  files above fails to recreate properly the Constructed Inventory. The end Result is the Constructed inventory is an empty shell.

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

infra.aap_configuration  
module: dispatch

## Steps to Reproduce
The issue can be reproduced on **AAP 2.5** with the following collection versions:

- **ansible-controller**: `4.6.9`
- **ansible-platform**: `2.5.20250312`
- **awx-awx**: `24.6.1`
- **infra-aap_configuration**: `3.1.0`
- **infra-eda_configuration**: `1.1.0`

### Version of ansible-core
```sh
ansible --version
ansible [core 2.17.3]
```

### Playbook Used
```yaml
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Format for 2.5
    aap_username: "your_login"
    aap_password: "your_password"
    aap_hostname: "URL_of_AAP2.5_environment"
    aap_validate_certs: false

  pre_tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: "opt/tower_backups/aap_casc_24_flattened"
        ignore_files: [controller_config.yml.template]
        extensions: ["yaml"]

  roles:
    # This is for 2.5
    - role: infra.aap_configuration.dispatch
      vars:
        gateway_configuration_dispatcher_roles:
          - role: gateway_organizations
            var: aap_organizations
            tags: organizations
            assign_galaxy_credentials_to_org: false
            assign_default_ee_to_org: false
            assign_notification_templates_to_org: false

        controller_configuration_dispatcher_roles:
          - role: controller_projects
            var: controller_projects
            tags: projects
          - role: controller_inventories
            var: controller_inventories
            tags: inventories
          - role: controller_inventory_sources
            var: controller_inventory_sources
            tags: inventory_sources
```

### How to Run the Playbook
```sh
ansible-playbook -vv dispatch_25.yml
```

## Expected Result
The constructed inventory should be created with all the defined `limit` and `source` variables from the inventory resource file as well as the source inventories.

## Actual Result
The constructed inventory gets created but is completely **empty**.

```

**Comment by djdanielsson** [comment]
please provide an example of the data you are passing to attempt to create the constructed inventory

**Comment by djdanielsson** [comment]
It appears that there is an issue with the way 2.4 filetree create exports data for constructed inventories and when the configuration is re-applied it will not be created as expected.

**Comment by djdanielsson** [comment]
@silvinux @ivarmu @adonisgarciac

**Comment by Tompage1994** [comment]
Once fixed, please ensure that the fix is also ported to aap_configuration_extended (If it applies)

**Comment by daleroux** [comment]
Hi team, besides filetree_create not properly creating an output for constructed inventories ( missing inventories sources ), dispatch also needs to be looked at as it doesn't recreate the constructed inventory properly. Limit field is recreated "empty" and so is "source vars". Please reopen the issue. Thank you!

**Comment by bontreger** [comment]
Is this the correct project?

**Comment by bontreger** [comment]
with the fixes made to constructed inventory, this probably needs to kick back over to infra.aap_configuration to resolve the import

**Comment by ivarmu** [comment]
Sorry for the delay, but I'm a little bit busy these days. I've taken a rapid look and I think the generated files through `filetree_create` are not correct, as the information may be placed into the wrong files. As can be seen here, `limits` and `source_vars` seems to go to the `inventory_source` instead of the `inventory` itself:

https://github.com/ansible/awx/blob/c3ee0c2d8a331951a71e74a3bac061f137859182/awx_collection/plugins/modules/inventory.py#L104-L132

So, if I'm right with this, a work around to this is to change these values from one file to the other one.

That said, a constructed inventory can have no inventory source associated with it, and still can have `limits` and `source_vars`, so I think the real problem here is that `awx.awx.inventory` and `ansible.controller.inventory` have these information misplaced, as these are fileds directly related to the constructed inventory itself. Below theres an output given by the AAP2.4 API for one example constructed inventory:

```json
{
    "id": 15,
    "type": "inventory",
    "url": "[/api/v2/constructed_inventories/15/](https://aapstdalone.bcnconsulting.com/api/v2/constructed_inventories/15/)",
    "related": {
        "named_url": "[/api/v2/constructed_inventories/CONTROLLER-Inventory-Constructed-Instances-001++CONTROLLER-ORG/](https://aapstdalone.bcnconsulting.com/api/v2/constructed_inventories/CONTROLLER-Inventory-Constructed-Instances-001++CONTROLLER-ORG/)",
        "created_by": "[/api/v2/users/1/](https://aapstdalone.bcnconsulting.com/api/v2/users/1/)",
        "modified_by": "[/api/v2/users/1/](https://aapstdalone.bcnconsulting.com/api/v2/users/1/)",
        "hosts": "[/api/v2/inventories/15/hosts/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/hosts/)",
        "variable_data": "[/api/v2/inventories/15/variable_data/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/variable_data/)",
        "script": "[/api/v2/inventories/15/script/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/script/)",
        "activity_stream": "[/api/v2/inventories/15/activity_stream/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/activity_stream/)",
        "job_templates": "[/api/v2/inventories/15/job_templates/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/job_templates/)",
        "ad_hoc_commands": "[/api/v2/inventories/15/ad_hoc_commands/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/ad_hoc_commands/)",
        "access_list": "[/api/v2/inventories/15/access_list/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/access_list/)",
        "object_roles": "[/api/v2/inventories/15/object_roles/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/object_roles/)",
        "instance_groups": "[/api/v2/inventories/15/instance_groups/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/instance_groups/)",
        "copy": "[/api/v2/inventories/15/copy/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/copy/)",
        "labels": "[/api/v2/inventories/15/labels/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/labels/)",
        "groups": "[/api/v2/inventories/15/groups/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/groups/)",
        "root_groups": "[/api/v2/inventories/15/root_groups/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/root_groups/)",
        "update_inventory_sources": "[/api/v2/inventories/15/update_inventory_sources/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/update_inventory_sources/)",
        "inventory_sources": "[/api/v2/inventories/15/inventory_sources/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/inventory_sources/)",
        "tree": "[/api/v2/inventories/15/tree/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/tree/)",
        "organization": "[/api/v2/organizations/17/](https://aapstdalone.bcnconsulting.com/api/v2/organizations/17/)",
        "input_inventories": "[/api/v2/inventories/15/input_inventories/](https://aapstdalone.bcnconsulting.com/api/v2/inventories/15/input_inventories/)",
        "constructed_url": "[/api/v2/constructed_inventories/15/](https://aapstdalone.bcnconsulting.com/api/v2/constructed_inventories/15/)"
    },
    "summary_fields": {
        "organization": {
            "id": 17,
            "name": "CONTROLLER-ORG",
            "description": "Organization in CONTROLLER"
        },
        "created_by": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "modified_by": {
            "id": 1,
            "username": "admin",
            "first_name": "",
            "last_name": ""
        },
        "object_roles": {
            "admin_role": {
                "description": "Can manage all aspects of the inventory",
                "name": "Admin",
                "id": 618
            },
            "update_role": {
                "description": "May update the inventory",
                "name": "Update",
                "id": 619
            },
            "adhoc_role": {
                "description": "May run ad hoc commands on the inventory",
                "name": "Ad Hoc",
                "id": 620
            },
            "use_role": {
                "description": "Can use the inventory in a job template",
                "name": "Use",
                "id": 621
            },
            "read_role": {
                "description": "May view settings for the inventory",
                "name": "Read",
                "id": 622
            }
        },
        "user_capabilities": {
            "edit": true,
            "delete": true,
            "copy": true,
            "adhoc": true
        },
        "labels": {
            "count": 0,
            "results": []
        }
    },
    "created": "2025-01-14T18:45:27.510424Z",
    "modified": "2025-01-15T11:29:23.033400Z",
    "name": "CONTROLLER-Inventory-Constructed-Instances-001",
    "description": "",
    "organization": 17,
    "kind": "constructed",
    "variables": "",
    "has_active_failures": false,
    "total_hosts": 2,
    "hosts_with_active_failures": 0,
    "total_groups": 30,
    "has_inventory_sources": false,
    "total_inventory_sources": 0,
    "inventory_sources_with_failures": 0,
    "pending_deletion": false,
    "prevent_instance_group_fallback": false,
    "source_vars": "---\ngroups:\n  target_group: group_names is search(\"ins002\") or group_names is search(\"web\")\nplugin: constructed\nstrict: true",
    "update_cache_timeout": 0,
    "limit": "target_group",
    "verbosity": 1
}
```

So... I belive the best way to resolve that issue is to fix the `awx.awx` and `ansible.controller` collections.

@sean-m-sullivan @Tompage1994 @djdanielsson what do you think?

**Comment by Tompage1994** [comment]
@ivarmu, I was just about to agree with you until I stumbled across the docs for creating a constructed inventory using the inventory module. [here](https://docs.ansible.com/ansible/latest/collections/awx/awx/inventory_module.html) it explains to create the inventory with `kind=constructed` but an inventory source will be automatically generated (hidden in the UI). The source has a specific name format we can utilise. So either we need to do some magic to work this all out and put things together or we need to let the user do that themselves. 

```
# You can create and modify constructed inventories by creating an inventory
# of kind "constructed" and then editing the automatically generated inventory
# source for that inventory.
- name: Add constructed inventory with two existing input inventories
  inventory:
    name: My Constructed Inventory
    organization: Default
    kind: constructed
    input_inventories:
      - "West Datacenter"
      - "East Datacenter"

- name: Edit the constructed inventory source
  inventory_source:
    # The constructed inventory source will always be in the format:
    # "Auto-created source for: <constructed inventory name>"
    name: "Auto-created source for: My Constructed Inventory"
    inventory: My Constructed Inventory
    limit: host3,host4,host6
    source_vars:
      plugin: constructed
      strict: true
      use_vars_plugins: true
      groups:
        shutdown: resolved_state == "shutdown"
        shutdown_in_product_dev: resolved_state == "shutdown" and account_alias == "product_dev"
      compose:
        resolved_state: state | default("running")
```
