### ISSUE TITLE
Bug: using infra.controller_configuration.filetree_create with the latest version error out

### ISSUE THREAD

**Issue by daleroux** [redhat-cop/infra.controller_configuration#38]
# Bug Report: `infra.controller_configuration.filetree_create` fails on AAP 2.4

## Summary

Using the role `infra.controller_configuration.filetree_create` on a 2.4 AAP environment ends in an error.

filetree_create end up in error  with v3.1.0  (of infra.controller_configuration)  but the job completes successfully with v2.11.0.

## Issue Type

- Bug Report

Collection version: `infra.controller_configuration:3.1.0` (latest)

## Environment Details

```console
ansible [core 2.17.3]

Collection                               Version
---------------------------------------- -------
ansible.controller                       4.5.21 
infra.controller_configuration           3.1.0  
```

**Controller Version:**  
Automation Controller Version: `4.6.2`

**Operating System:**  
Fedora

## Desired Behavior

```bash
$ ansible-playbook filetree_create.yml -e '{output_path:/home/dleroux/cases/04057817/24/output_flat,flatten_output:true}'
```

Should create all files under directory `output_flat`.

## Actual Behavior

```text
TASK [infra.controller_configuration.filetree_create : Add current inventory source to the inventory sources flat file] ****
task path: /home/dleroux/cases/04057817/24/collections/ansible_collections/infra/controller_configuration/roles/filetree_create/tasks/inventory_sources.yml:21
File lookup using /home/dleroux/cases/04057817/24/collections/ansible_collections/infra/controller_configuration/roles/filetree_create/templates/current_inventory_sources.j2 as file
Loading collection ansible.controller from /home/dleroux/cases/04057817/24/collections/ansible_collections/ansible/controller
fatal: [localhost]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'source_project'\n\nThe error appears to be in '/home/dleroux/cases/04057817/24/collections/ansible_collections/infra/controller_configuration/roles/filetree_create/tasks/inventory_sources.yml': line 21, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: \"Add current inventory source to the inventory sources flat file\"\n      ^ here\n"
}
```

## Playbook Example

```yaml
---
- name: Export controller configuration
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    vault.yml
  vars:
    controller_username: admin
    controller_password: something
    controller_hostname: controller.example.com
    controller_validate_certs: false
    flatten_output: true
    output_path: /home/dleroux/cases/04057817/24/output_flat

  pre_tasks:
    - name: "Setup authentication (block)"
      block:
        - name: "Get the Authentication Token for the future requests"
          ansible.builtin.uri:
            url: "https://{{ controller_hostname }}/api/v2/tokens/"
            user: "{{ controller_username }}"
            password: "{{ controller_password }}"
            method: POST
            force_basic_auth: true
            validate_certs: "{{ controller_validate_certs }}"
            status_code: 201
          register: authtoken_res

        - name: "Set the oauth token to be used since now"
          ansible.builtin.set_fact:
            controller_oauthtoken: "{{ authtoken_res.json.token }}"
            controller_oauthtoken_url: "{{ authtoken_res.json.url }}"
      no_log: "{{ controller_configuration_filetree_create_secure_logging | default('false') }}"
      when: controller_oauthtoken is not defined
      tags:
        - always

  roles:
    - infra.controller_configuration.filetree_create

  post_tasks:
    - name: "Delete the Authentication Token used"
      ansible.builtin.uri:
        url: "https://{{ controller_hostname }}{{ controller_oauthtoken_url }}"
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        method: DELETE
        force_basic_auth: true
        validate_certs: "{{ controller_validate_certs }}"
        status_code: 204
      when: controller_oauthtoken_url is defined
```

## Steps to Reproduce

Run the following command:

```bash
ansible-playbook filetree_create.yml -e '{output_path:/home/dleroux/cases/04057817/24/output_flat,flatten_output:true}' -vvvv
```

## Configuration Snippet

Partial `ansible.cfg`:

```ini
[defaults]
inventory= ./inventory
remote_user=ansible
server_list = automation_hub,galaxy
collections_paths = ./collections:/usr/share/ansible/collections
```
