### ISSUE TITLE
Workflow Job Template Nodes Not Deleted When Removed from controller_workflows in AAP 2.4

### ISSUE THREAD

**Issue by kakashiiMF** [redhat-cop/infra.controller_configuration#46]
# Bug: Workflow Job Template Nodes Not Deleted When Removed from controller_workflows in AAP 2.4

## Summary
When removing a node (e.g., Node C) from a Workflow Job Template in the `controller_workflows` variable using the `infra.controller_configuration` collection with AAP 2.4, the node is not deleted in Ansible Automation Platform (AAP). The `object_diff` and `dispatch` roles correctly identify the node as absent (`set_absent=true`), but the `workflow_job_templates` role fails to remove it from the Workflow Job Template in AAP.

## Issue Type
- [x] Bug Report
- [ ] Feature Request
- [ ] Documentation Issue

## Environment
- **AAP Version**: 2.4 (Automation Controller 4.5.20)
- **infra.controller_configuration Version**: 2.11.0
- **ansible.controller Version**: 4.5.5
- **Ansible Version**: 2.15.13
- **Operating System**: RHEL 8
- **Execution Environment**: ansible-automation-platform-24/ee-supported-rhel8:latest

## Steps to Reproduce
1. Create a Workflow Job Template in AAP 2.4 with three nodes (A, B, C):
   - Node A: Job Template "Job Template A", success to Node B.
   - Node B: Job Template "Job Template B", no successors.
   - Node C: Job Template "Job Template C", no successors.
2. Define the Workflow Job Template in a CasC YAML file (e.g., `workflows.yml`) with only Nodes A and B, excluding Node C.
3. Run a playbook using `infra.controller_configuration.filetree_read`, `object_diff`, and `dispatch` roles to apply the configuration.
4. Check the Workflow Job Template in AAP’s Visualizer.

## Expected Behavior
- The `object_diff` role should identify Node C as absent (`state: absent`) in `__workflow_job_templates_difference` since it is not in `controller_workflows`.
- The `dispatch` role’s `workflow_job_templates` task should delete Node C from the Workflow Job Template.
- The Visualizer should show only Nodes A and B.

## Actual Behavior
- The `object_diff` role does not include Node C in `__workflow_job_templates_difference` with `state: absent`.
- The `dispatch` role’s `workflow_job_templates` task does not delete Node C, as it relies on the incorrect diff.
- Node C remains in the Workflow Job Template in AAP Visualizer.

## Steps to Reproduce
1. Create Job Templates "Job Template A", "Job Template B", and "Job Template C" in AAP.
2. Configure a Workflow Job Template named "My Workflow" with three nodes (A, B, C) via the AAP UI or API.
3. Define the Workflow Job Template in a CasC YAML file with only Nodes A and B, excluding Node C.
4. Run a playbook using `infra.controller_configuration.filetree_read`, `object_diff`, and `dispatch` roles.
5. Check the Workflow Job Template in AAP’s Visualizer and debug `__workflow_job_templates_difference`.

### CasC File (`yaml/workflows.yml`)
```yaml
controller_workflows:
  - name: "My Workflow"
    organization: "Default"
    nodes:
      - identifier: "node_a"
        unified_job_template: "Job Template A"
        success_nodes: ["node_b"]
        failure_nodes: []
        always_nodes: []
      - identifier: "node_b"
        unified_job_template: "Job Template B"
        success_nodes: []
        failure_nodes: []
        always_nodes: []
```

### Playbook (`manage_workflow.yml`)
```yaml
- name: Manage AAP Workflow Job Template
  hosts: localhost
  connection: local
  collections:
    - ansible.controller
    - infra.controller_configuration
  vars:
    controller_host: "https://aap.example.com"
    controller_username: "admin"
    controller_password: "your-password"
    controller_validate_certs: false
    ansible_verbosity: 3
  tasks:
    - block:
        - name: Import role filetree_read
          ansible.builtin.import_role:
            name: infra.controller_configuration.filetree_read

        - name: Debug controller_workflows
          tags: workflow_job_templates
          ansible.builtin.debug:
            var: controller_workflows
            verbosity: 1

        - name: Import role object_diff
          ansible.builtin.import_role:
            name: infra.controller_configuration.object_diff
          vars:
            controller_configuration_object_diff_tasks:
              - {name: workflow_job_templates, var: controller_workflows, tags: workflow_job_templates}
          register: diff_result

        - name: Import role dispatch
          ansible.builtin.import_role:
            name: infra.controller_configuration.dispatch
          vars:
            controller_configuration_dispatcher_roles:
              - {role: workflow_job_templates, var: controller_workflows, tags: workflow_job_templates}
          register: dispatch_result

```

## Precondition
- Create Job Templates "Job Template A", "Job Template B", and "Job Template C" in AAP.
- Initially configure the Workflow Job Template "My Workflow" with Nodes A, B, and C via the AAP UI or API.

## Logs and Outputs
- `diff_result` does not list Node C in `__workflow_job_templates_difference` with `state: absent`.
- No errors in `dispatch_result`, but Node C persists in AAP Visualizer.
```yaml
TASK [infra.controller_configuration.object_diff : Find the difference of Workflow Job Templates between what is on the Controller versus CasC on SCM] *******************************************************
compare_list_reduced: [{'name': 'qly-aap', 'organization': 'af.sup.proc.real.nsm'}, {'name': 'My Workflow', 'organization': 'af.sup.proc.real.nsm'}]
api_list_reduced: [{'name': 'qly-aap', 'organization': 'af.sup.proc.real.nsm'}]
ok: [vscontroller.qly.aap.sys.sibs.pt] => {"ansible_facts": {"__workflow_job_templates_difference": []}, "changed": false}
```

## Additional Context
- The issue stems from the `object_diff` role’s `controller_role_plugin` failing to identify nodes absent from `controller_workflows` but present in AAP’s Workflow Job Template.
- AAP API query (`/api/v2/workflow_job_templates/<id>/workflow_nodes/`) confirms Node C’s persistence.

<img width="660" alt="Image" src="https://github.com/user-attachments/assets/f26c3f32-3eea-4740-a626-a5b6575f3e0d" />
[job_output.txt](https://github.com/user-attachments/files/20230165/job_output.txt)

<img width="660" alt="Image" src="https://github.com/user-attachments/assets/6fff0b94-b21e-40bf-9ce9-f13bf14d3abd" />

- Manual API deletion of Node C (`DELETE /api/v2/workflow_job_template_nodes/<node_c_id>`) works.
- This issue occurs in AAP 2.4, using `infra.controller_configuration` for configuration management.

## Possible Fix
- Update the `controller_role_plugin` lookup plugin to correctly compare Workflow Job Template nodes and mark absent nodes (`state: absent`) in `__workflow_job_templates_difference`.
- Ensure the `workflow_job_templates` role processes absent nodes correctly, issuing API `DELETE` calls when `set_absent=true`.

## References
- [AAP Config as Code Docs](https://redhat-cop.github.io/controller_configuration/)
- [Ansible Controller Collection](https://github.com/ansible/awx)

## Labels
- bug
- object_diff
- workflow_job_templates
- controller_role_plugin
- AAP 2.4
