### ISSUE TITLE
filetree_create generates malformed YAML for constructed inventories (plugin key misaligned under source_vars)

### ISSUE THREAD

**Issue by daleroux** [redhat-cop/infra.controller_configuration#49]
## Summary

When using filetree_create to export configuration from an AAP 2.4 environment, the generated inventories.yaml file contains improperly formatted YAML for constructed inventory source_vars. Specifically, the plugin: constructed line is misaligned by one space, causing import failures with dispatch in AAP 2.5.

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

ansible [core 2.16.11]

infra.controller_configuration  3.1.2  (latest)
ansible.controller   4.5.22 (latest for 2.4)

Ansible Automation Platform Controller 4.5.8

- ansible installation method: OS package

## OS / ENVIRONMENT

Red Hat Enterprise Linux release 9.4 (Plow)

## Desired Behavior

```
source_vars:
  plugin: constructed
  strict: true
  groups:
    target_group: ('linuxservers' in group_names)
```

## Actual Behavior

The generated inventories.yaml for constructed inventories contains an incorrectly indented plugin line under source_vars, which causes the YAML to be invalid and results in a failed import.

```
source_vars:
   plugin: constructed   # <- there's an extra space before 'plugin' that needs to be removed
  strict: true
  groups:
    target_group: ('linuxservers' in group_names)
```

## STEPS TO REPRODUCE

a reproducer is described in case 04132323 with instructions on how to access it.
